### ISSUE TITLE
Multiple entity managers

### ISSUE THREAD

**Issue by davidnectarestudio** [theofidry/AliceBundle#74]
Hi.

I'm trying to load fixtures from multiple Doctrine connections. Check this config:

```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: 'default'
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            externals:
                url: '%env(resolve:DATABASE_EXTERNALS_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: 'default'
        entity_managers:
            default:
                connection: 'default'
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
                mappings:
                    App:
                        is_bundle: false
                        type: 'attribute'
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: 'App'
            externals:
                connection: 'externals'
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
                mappings:
                    ExternalApp:
                        is_bundle: false
                        type: 'attribute'
                        dir: '%kernel.project_dir%/src/Entity/Externals'
                        prefix: 'App\Entity\Externals'
                        alias: 'ExternalApp'
```

![Captura de pantalla 2025-01-15 a les 17 22 36](https://github.com/user-attachments/assets/183bf80d-8ce2-4e70-8ef9-be8ee6ba63d0)

Then I'm writing my test environment fixtures here, but it seems that no data are stored inside first connection database. What is happening? Can I check something to be sure?

```yaml
# fixtures/test/test-fixtures.yaml
App\Entity\Main\User:
    user_{1..9}:
        username: 'user<current()>'
        password: 'password<current()>'
        enabled: '<boolean()>'
        roles:
            - 'ROLE_USER'

App\Entity\Externals\BedsOnline\Country:
    country_{1..9}:
        name: '<country()>'
        isoCode: '<countryISOAlpha3()>'
        code: '<countryCode()>'
```

I only see stored external fixtures.
