### ISSUE TITLE
Same fixtures repeatedly generated

### ISSUE THREAD

**Issue by Chrisissorry** [theofidry/AliceBundle#83]
Not sure if I am losing my mind here, but I ran into a very suspicious issue. My fixtures look like this:

```yaml
App\Entity\Employee (template):
    employee_template: 
        firstName: <firstName()>
        lastName: <lastName()>
```

Still, the resulting database content is always exactly the same. After every fixture run.

`php bin/console hautelook:fixtures:load --no-interaction --purge-with-truncate -v`

Here's what I tried to narrow down the problem:

* Changed DB content manually, it is reflected in the UI
* Changed fixture, e.g. replacing `firstName()` with 'Robert' - works, everyone is called Robert now
* Dropped the whole DB, recreated the schema, ran the fixtures - same content again
* Searched the whole codebase for the names that get produced, no result

Thus, I can attest that:

* I am connected to the right DB
* It's not some kind of strange DB caching mechanism
* It's not any other fixture / migration that produces these results

Is there some kind of cache, mb. related to faker, which I need to clear here?
